[tool.commitizen]
name = "cz_conventional_commits"
version = "0.3.2"
version_files = [
    "setup.cfg:version",
    "docs/conf.py: release"
]
tag_format = "$version"
bump_message = "bump: $current_version → $new_version"
