# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test app and bump

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pylint
      run: |
        pylint sshcon
    - name: Ensure ssh is installed
      run: sudo apt update; sudo apt -y install openssh-server
    # - name: Check config
    #   run: |
    #     cat > sshd_config <<EOF
    #       SyslogFacility AUTHPRIV
    #       PermitRootLogin yes
    #       AuthorizedKeysFile	.ssh/authorized_keys
    #       PasswordAuthentication yes
    #       ChallengeResponseAuthentication no
    #       UsePAM yes
    #       UseDNS no
    #       X11Forwarding no
    #       PrintMotd no
    #       MaxSessions 100
    #     EOF
    #     sudo mv sshd_config /etc/ssh/sshd_config
    #     sudo systemctl restart ssh
    - name: Create ssh key
      run: >
        ssh-keygen -t rsa -b 4096 -N '' -f ~/.ssh/id_rsa
    - name: Add key to auth file
      run: >
        cat ~/.ssh/id_rsa.pub | tee -a ~/.ssh/authorized_keys
    - name: Ensure the owner of the key is correct
      run: |
        chmod 600 ~/.ssh/authorized_keys
        chmod 700 ~/.ssh
        sudo chmod -c 0755 ~/
        ls -la ~/.ssh
    - name: Test SSH connection to localhost
      run: >
        ssh -i ~/.ssh/id_rsa -o BatchMode=yes -o StrictHostKeyChecking=no $(whoami)@localhost        

    - name: Test with pytest
      run: |
        pip install -e .
        pytest
      env:
        SSHHOST: localhost
        SSHUSER: runner
        SSHKEY: /home/runner/.ssh/id_rsa

  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    needs: test_app
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}